use sisqsf;
insert into usuarios(ClaveUsuario,NoControl,Nombre,EsAlumno,Telefono,Correo)
values
(null,'S16120302','Luis Alberto Ignacio Esteban','Si','4451236073','beto@gmail.com'),
(null,'S16121234','Cristian Benigno Morales Morales','Si','4454554289','beni@gmail.com'),
(null,'S16124569','Briyant Ivan Perez Reyes','Si','4451403399','DotZeus@gmail.com');

insert into qsf(ClaveQSF,Prioridad,Estatus,Departamento,Tipo_Servicio,Descripcion,Fecha,UsuarioSolicitante)
values
(null,'Baja','No iniciada','Calidad','Sugerencia','No hay clases por el COVID-19', 20190414,1),
(null,'Media','En proceso','Academico','Queja','No hay clases por el COVID-19', 20180512,3),
(null,'Baja','Finalizada','Planeacion','Sugerencia','No hay clases por el COVID-19', 20160320,2),
(null,'Alta','No iniciada','Vinculacion','Felicitacion','No hay clases por el COVID-19', 20170508,4),
(null,'Media','En proceso','Academico','Queja','No hay clases por el COVID-19', 20190118,3),
(null,'Alta','No iniciada','Planeacion','Sugerencia','No hay clases por el COVID-19', 20190514,2),
(null,'Baja','Rechazada','Calidad','Sugerencia','No hay clases por el COVID-19', 20160810,3),
(null,'Alta','En proceso','Vinculacion','Queja','No hay clases por el COVID-19', 20190511,4),
(null,'Alta','Finalizada','Academico','Sugerencia','No hay clases por el COVID-19', 20181019,2),
(null,'Media','No iniciada','Planeacion','Felicitacion','No hay clases por el COVID-19', 20190505,1),
(null,'Alta','Rechazada','Administracion','Queja','No hay clases por el COVID-19', 20171223,3),
(null,'Media','En proceso','Vinculacion','Sugerencia','No hay clases por el COVID-19', 20190621,2),
(null,'Baja','No iniciada','Academico','Sugerencia','No hay clases por el COVID-19', 20180529,1),
(null,'Media','En proceso','Vinculacion','Felicitacion','No hay clases por el COVID-19', 20190911,3),
(null,'Alta','No iniciada','Calidad','Sugerencia','No hay clases por el COVID-19', 20160508,2),
(null,'Baja','Finalizada','Academico','Felicitacion','No hay clases por el COVID-19', 20180725,4),
(null,'Media','Rechazada','Planeacion','Queja','No hay clases por el COVID-19', 20160509,1),
(null,'Baja','En proceso','Vinculacion','Sugerencia','No hay clases por el COVID-19', 20190519,3),
(null,'Alta','No iniciada','Academico','Felicitacion','No hay clases por el COVID-19', 20180414,1),
(null,'Baja','En proceso','Planeacion','Queja','No hay clases por el COVID-19', 20190518,2),
(null,'Alta','No iniciada','Calidad','Sugerencia','No hay clases por el COVID-19', 20170218,3),
(null,'Baja','En proceso','Administracion','Sugerencia','No hay clases por el COVID-19', 20190117,4),
(null,'Media','Rechazada','Vinculacion','Sugerencia','No hay clases por el COVID-19', 20160513,1),
(null,'Baja','No iniciada','Academico','Felicitacion','No hay clases por el COVID-19', 20190708,2),
(null,'Media','Rechazada','Planeacion','Queja','No hay clases por el COVID-19', 20170504,3),
(null,'Baja','En proceso','Academico','Sugerencia','No hay clases por el COVID-19', 20191002,4),
(null,'Alta','No iniciada','Calidad','Sugerencia','No hay clases por el COVID-19', 20161108,1),
(null,'Media','Finalizada','Vinculacion','Sugerencia','No hay clases por el COVID-19', 20180503,3),
(null,'Baja','En proceso','Academico','Felicitacion','No hay clases por el COVID-19', 20190918,2),
(null,'Media','No iniciada','Calidad','Queja','No hay clases por el COVID-19', 20170528,1),
(null,'Baja','Rechazada','Administracion','Sugerencia','No hay clases por el COVID-19', 20191219,2),
(null,'Media','No iniciada','Academico','Sugerencia','No hay clases por el COVID-19', 20171113,4),
(null,'Alta','Finalizada','Vinculacion','Felicitacion','No hay clases por el COVID-19', 20190312,3),
(null,'Baja','No iniciada','Academico','Sugerencia','No hay clases por el COVID-19', 20160517,1),
(null,'Alta','Rechazada','Planeacion','Queja','No hay clases por el COVID-19', 20160813,2),
(null,'Alta','En proceso','Calidad','Sugerencia','No hay clases por el COVID-19', 20190526,3),
(null,'Baja','Finalizada','Planeacion','Felicitacion','No hay clases por el COVID-19', 20170326,4),
(null,'Media','No iniciada','Administracion','Sugerencia','No hay clases por el COVID-19', 20190816,4),
(null,'Baja','En proceso','Administracion','Queja','No hay clases por el COVID-19', 20190506,2),
(null,'Media','No iniciada','Planeacion','Felicitacion','No hay clases por el COVID-19', 20180208,3),
(null,'Baja','Rechazada','Vinculacion','Sugerencia','No hay clases por el COVID-19', 20161019,4),
(null,'Alta','En proceso','Academico','Queja','No hay clases por el COVID-19', 20191226,2),
(null,'Baja','No iniciada','Vinculacion','Felicitacion','No hay clases por el COVID-19', 20170912,3),
(null,'Media','No iniciada','Academico','Sugerencia','No hay clases por el COVID-19', 20190614,4),
(null,'Baja','Finalizada','Calidad','Queja','No hay clases por el COVID-19', 20190116,2),
(null,'Alta','En proceso','Vinculacion','Sugerencia','No hay clases por el COVID-19', 20180308,4),
(null,'Media','No iniciada','Administracion','Felicitacion','No hay clases por el COVID-19', 20171121,1),
(null,'Baja','En proceso','Academico','Queja','No hay clases por el COVID-19', 20160526,3),



(null,'Baja','Rechazada','Administracion','Sugerencia','No hay clases por el COVID-19', date(now()),2),
(null,'Media','No iniciada','Academico','Sugerencia','No hay clases por el COVID-19', date(now()),4),
(null,'Alta','Finalizada','Vinculacion','Felicitacion','No hay clases por el COVID-19', date(now()),3),
(null,'Baja','No iniciada','Academico','Sugerencia','No hay clases por el COVID-19', date(now()),1),
(null,'Alta','Rechazada','Planeacion','Queja','No hay clases por el COVID-19', date(now()),2),
(null,'Alta','En proceso','Calidad','Sugerencia','No hay clases por el COVID-19', date(now()),3),
(null,'Baja','Finalizada','Planeacion','Felicitacion','No hay clases por el COVID-19', date(now()),4),
(null,'Media','No iniciada','Administracion','Sugerencia','No hay clases por el COVID-19', date(now()),4),
(null,'Baja','En proceso','Administracion','Queja','No hay clases por el COVID-19', date(now()),2),
(null,'Media','No iniciada','Planeacion','Felicitacion','No hay clases por el COVID-19', date(now()),3),
(null,'Baja','Rechazada','Vinculacion','Sugerencia','No hay clases por el COVID-19', date(now()),4),
(null,'Alta','En proceso','Academico','Queja','No hay clases por el COVID-19', date(now()),2),
(null,'Baja','No iniciada','Vinculacion','Felicitacion','No hay clases por el COVID-19', date(now()),3),
(null,'Media','No iniciada','Academico','Sugerencia','No hay clases por el COVID-19', date(now()),4),
(null,'Baja','Finalizada','Calidad','Queja','No hay clases por el COVID-19', date(now()),2),
(null,'Alta','En proceso','Vinculacion','Sugerencia','No hay clases por el COVID-19', date(now()),4),
(null,'Media','No iniciada','Administracion','Felicitacion','No hay clases por el COVID-19', date(now()),1),
(null,'Baja','En proceso','Academico','Queja','No hay clases por el COVID-19', date(now()),3);
